swagger: "2.0"
info:
  title: beego Test API
  description: |
    beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /auth/login:
    post:
      tags:
      - auth
      description: |-
        Login
        <br>
      operationId: AuthenticationController.Create
      parameters:
      - in: body
        name: body
        description: body for Authentication content
        required: true
        schema:
          $ref: '#/definitions/models.AuthenticationDTO'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.UserResponseDTO'
        "403":
          description: body is empty
  /auth/verify-otp:
    post:
      tags:
      - auth
      description: |-
        Login
        <br>
      operationId: AuthenticationController.Verify OTP
      parameters:
      - in: body
        name: body
        description: body for Authentication content
        required: true
        schema:
          $ref: '#/definitions/models.AuthenticationDTO'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.UserResponseDTO'
        "403":
          description: body is empty
definitions:
  models.AuthenticationDTO:
    title: AuthenticationDTO
    type: object
    properties:
      Password:
        type: string
      Username:
        type: string
  models.SignUpDTO:
    title: SignUpDTO
    type: object
    properties:
      Dob:
        type: string
      Email:
        type: string
      Gender:
        type: string
      Name:
        type: string
      Password:
        type: string
  models.UpdateUserRequestDTO:
    title: UpdateUserRequestDTO
    type: object
    properties:
      Address:
        type: string
      Dob:
        type: string
      FullName:
        type: string
      Gender:
        type: string
      MaritalStatus:
        type: string
      PhoneNumber:
        type: string
      Username:
        type: string
  models.UserResponseDTO:
    title: UserResponseDTO
    type: object
    properties:
      StatusCode:
        type: integer
        format: int64
      StatusDesc:
        type: string
      User:
        $ref: '#/definitions/models.Users'
  models.UsernameDTO:
    title: UsernameDTO
    type: object
    properties:
      Username:
        type: string
  models.Users:
    title: Users
    type: object
    properties:
      Active:
        type: integer
        format: int64
      Address:
        type: string
      CreatedBy:
        type: integer
        format: int64
      DateCreated:
        type: string
        format: datetime
      DateModified:
        type: string
        format: datetime
      Dob:
        type: string
        format: datetime
      Email:
        type: string
      FullName:
        type: string
      Gender:
        type: string
      IdNumber:
        type: string
      IdType:
        type: string
      IsVerified:
        type: boolean
      MaritalStatus:
        type: string
      ModifiedBy:
        type: integer
        format: int64
      Password:
        type: string
      PhoneNumber:
        type: string
      UserId:
        type: integer
        format: int64
      UserType:
        type: integer
        format: int64
      Username:
        type: string
tags:
- name: auth
  description: |
    AuthenticationController operations for Authentication
