appname = authentication_service
httpport = 5080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true

customerBaseUrl = http://localhost:5083
# host = "https://orange-falcons-enter.loca.lt"
host = "https://authentication.mestechgh.com"

pguser = ${DB_USER}
pgpass = ${DB_PASSWORD}
pghost = ${DB_HOST}
pgport = ${DB_PORT}
pgdb   = ${DB_NAME}
pgtest = "THIS IS A TEST"

# sqlconn = eappuser:Mtts33R@16JuN3LLb@tcp(localhost:3306)/ecommerce_authentication?parseTime=true&loc=UTC